### ISSUE TITLE
pkg_install should work in Windows

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#387]
The current iteration of `pkg_install` was only tested on Linux and macOS.  I currently do not have a Windows development environment available, so things were likely to be missed.

In particular, this failure comes to mind: https://buildkite.com/bazel/rules-pkg/builds/968.  This might be caused by `RUNFILES_DIR` not being in the command's environment.

This is within tests only, though, so `bazel run`ning it may "just work".

Confirm and investigate.

**Comment by redsun82** [comment]
Unfortunately windows package install does not work on Windows as far as I could test, with an error like:
```
Traceback (most recent call last):
  File "C:\Users\RUNNER~1\AppData\Local\Temp\Bazel.runfiles_b22e6u2k\runfiles\_main\go\create_extractor_pack.py", line 16, in <module>
    main(sys.argv)
  File "C:\Users\RUNNER~1\AppData\Local\Temp\Bazel.runfiles_b22e6u2k\runfiles\_main\go\_create_extractor_pack_install_script.py", line 195, in main
    installer.include_manifest_path(f)
  File "C:\Users\RUNNER~1\AppData\Local\Temp\Bazel.runfiles_b22e6u2k\runfiles\_main\go\_create_extractor_pack_install_script.py", line 123, in include_manifest_path
    with open(path, 'r') as fh:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'go/_create_extractor_pack_install_script-install-manifest.json'
```

I might be able to do some debugging and maybe come up with a patch for this in the coming days.
