### ISSUE TITLE
Builds failing with `--incompatible_disallow_empty_glob`

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_pkg#827]
On `0.10.1` my builds fail with the following issue likely due to things being omitted from the release artifacts.
```
ERROR: Traceback (most recent call last):
	File "/home/user/.cache/bazel/_bazel_user/e497939fa198e6588dc55730b8a3a7f2/external/rules_pkg/pkg/rpm/BUILD", line 20, column 9, in <toplevel>
		glob([
Error in glob: glob pattern '*.bzl' didn't match anything, but allow_empty is set to False (the default value of allow_empty can be set with --incompatible_disallow_empty_glob).
ERROR: package contains errors: pkg/rpm: Traceback (most recent call last):
	File "/home/user/.cache/bazel/_bazel_user/e497939fa198e6588dc55730b8a3a7f2/external/rules_pkg/pkg/rpm/BUILD", line 20, column 9, in <toplevel>
		glob([
Error in glob: glob pattern '*.bzl' didn't match anything, but allow_empty is set to False (the default value of allow_empty can be set with --incompatible_disallow_empty_glob).
ERROR: Skipping '@rules_pkg//...': Error evaluating '@rules_pkg//...': error loading package '@@rules_pkg//pkg/rpm': Package 'pkg/rpm' contains errors
ERROR: Error evaluating '@rules_pkg//...': error loading package '@@rules_pkg//pkg/rpm': Package 'pkg/rpm' contains errors
```

**Comment by aiuto** [comment]
I believe this is fixed by #825
