### ISSUE TITLE
pkg_tar cannot handle non-ascii names with python 2

### ISSUE THREAD

**Issue by kriswuollett** [bazelbuild/rules_pkg#84]
In `archive.py` this line throws `UnicodeDecodeError` when encountering non-ASCII filename when repacking a tar file:

```python
name = '.' + root + name.lstrip('.')
```

I encountered this specifically when trying to repackage [go1.12.9.linux-amd64.tar.gz](https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz) into a Debian package. Grep for `issue27836` in the linked tar file for the troublesome files, specifically `./go/test/fixedbugs/issue27836.dir/\xc3\x84foo.go'`.

Running Ubuntu 18.04, Bazel 0.29.9, along with my `.bazelrc`:

```
build --host_force_python=PY2
test --host_force_python=PY2
```

I was forced to set `PY2` because I got a previous error about rules_pkg being written for Python 2 but was somehow using Python 3 with Bazel.

**Comment by aiuto** [comment]
Is anything blocking you from updating to Python3. We are considering dropping python2 backwards support.

**Comment by kriswuollett** [comment]
Nothing was blocking me from updating to Python3. I merely had both `python3` and `python2.7` installed on my system and my repository was nearly empty except for trying to build a single Debian package for go. There was no Python targets in my repository. Somehow `rules_pkg` wasn't happy with my setup which I think had `python3` as my default.

**Comment by kriswuollett** [comment]
Not sure if https://github.com/bazelbuild/bazel/issues/374 ("Allow any characters in filenames") landing has the potential to be related soon as well?

**Comment by whilp** [comment]
FWIW, I observe a `UnicodeEncodeError` (not decode) at a similar spot with Python 3.6.

https://github.com/bazelbuild/rules_pkg/blob/cb54c427343aa48c32e3c09ddcc8f6316cdbd5a6/pkg/archive.py#L232

`BUILD.bazel` has:

```python
load("@rules_pkg//:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "usr_local",
    package_dir = "usr/local",
    deps = [
        "@go_sdk_linux//file",
    ],
)
```

`WORKSPACE` has:

```python
    go_version = "1.12.9"
    http_file(
        name = "go_sdk_linux",
        sha256 = "ac2a6efcc1f5ec8bdc0db0a988bb1d301d64b6d61b7e8d9e42f662fbb75a2b9b",
        urls = ["https://dl.google.com/go/go{0}.linux-amd64.tar.gz".format(go_version)],
        downloaded_file_path = "go_sdk_linux.tgz",
    )
```

<details>
<summary> stack trace </summary>

```
ERROR: /workspace/project/images/devcontainer/BUILD.bazel:17:1: PackageTar images/devcontainer/usr_local.tar failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d809f0add43125a2d7b06c037864591c/execroot/project/bazel-out/host/bin/external/rules_pkg/build_tar.runfiles/rules_pk
g/build_tar.py", line 387, in <module>
    main(FLAGS(sys.argv))
  File "/root/.cache/bazel/_bazel_root/d809f0add43125a2d7b06c037864591c/execroot/project/bazel-out/host/bin/external/rules_pkg/build_tar.runfiles/rules_pkg/build_tar.py", line 378, in main
    output.add_tar(tar)
  File "/root/.cache/bazel/_bazel_root/d809f0add43125a2d7b06c037864591c/execroot/project/bazel-out/host/bin/external/rules_pkg/build_tar.runfiles/rules_pkg/build_tar.py", line 226, in add_tar
    self.tarfile.add_tar(tar, numeric=True, root=root)
  File "/root/.cache/bazel/_bazel_root/d809f0add43125a2d7b06c037864591c/execroot/project/bazel-out/host/bin/external/rules_pkg/build_tar.runfiles/rules_pkg/archive.py", line 418, in add_tar
    self._addfile(tarinfo, intar.extractfile(tarinfo))
  File "/root/.cache/bazel/_bazel_root/d809f0add43125a2d7b06c037864591c/execroot/project/bazel-out/host/bin/external/rules_pkg/build_tar.runfiles/rules_pkg/archive.py", line 232, in _addfile
    self.tar.addfile(info, fileobj)
  File "/usr/lib/python3.6/tarfile.py", line 1974, in addfile
    buf = tarinfo.tobuf(self.format, self.encoding, self.errors)
  File "/usr/lib/python3.6/tarfile.py", line 814, in tobuf
    return self.create_gnu_header(info, encoding, errors)
  File "/usr/lib/python3.6/tarfile.py", line 842, in create_gnu_header
    if len(info["name"].encode(encoding, errors)) > LENGTH_NAME:
UnicodeEncodeError: 'ascii' codec can't encode character '\xc4' in position 45: ordinal not in range(128)
----------------
Note: The failure of target @rules_pkg//:build_tar (with exit code 1) may have been caused by the fact that it is a Python 2 program that was built in the host configuration, which uses Python 3. You can change the host configuration (for the entire build) to instead use Python 2 by setting --host_force_python=PY2.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //images/devcontainer:devcontainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 26.768s, Critical Path: 5.15s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by whilp** [comment]
FWIW, ensuring that build (and test) actions run in a utf-8 locale does the trick:

```
build --action_env=LANG=C.UTF-8
test --action_env=LANG=C.UTF-8
```

**Comment by aiuto** [comment]
closing because python2
